### ISSUE TITLE
Handle checkbox with phx-click but no form

### ISSUE THREAD

**Issue by ftes** [germsvel/phoenix_test#101]
Checkboxes (and other inputs) may be used outside of forms to trigger `phx-click` and `phx-change` events that are specified on the input (not on the form).

Either
1. `check/2` could support this use case or (preferred)
2. add a dedicated `click_checkbox/2`

In both cases, the `name` attribute should not be required.

## Current behaviour
Calling `check/2` on a checkbox outside of a form results in

```ex
     ** (ArgumentError) Could not find "form" for an element with selector "#my-checkbox-id".

     Found other potential "form":
```

If there is no `name` attribute on that checkbox, it fails even earlier:

```ex
     ** (FunctionClauseError) no function clause matching in Regex.scan/3
```

**Comment by germsvel** [comment]
Yeah, this is definitely a use case we should support. Thanks for opening the issue!

**Comment by germsvel** [comment]
I think this was resolved by https://github.com/germsvel/phoenix_test/pull/116. I'm going to close it. If you think it's not addressed, happy to reopen it.
