### ISSUE TITLE
Uncheck checkbox without hidden input error

### ISSUE THREAD

**Issue by totaltrash** [germsvel/phoenix_test#104]
If you have a checkbox without a hidden:

```html
<input type="checkbox" name="roles[]" id="role_reader" value="reader" checked />
<label for="role_reader">Reader</label>
```

```elixir
uncheck(session, "Reader")
```

Results in:

```
** (ArgumentError) Could not find element with selector "input[type='hidden'][name='roles[]']"
code: |> uncheck("Reader")
```

**Comment by totaltrash** [comment]
I've been unable to replicate this in a test so far, I think it's probably a combination of validating the form using `phx-change`, but I thought it was a weird error (could be Phoenix.LiveViewTest maybe?). I'll have another crack hopefully later this week

**Comment by germsvel** [comment]
@totaltrash I think that's expected. You can't really "uncheck" a checkbox. In a form, it needs to have a corresponding hidden input. 

Here's a note from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox): 

> Note: If a checkbox is unchecked when its form is submitted, neither the name nor the value is submitted to the server. There is no HTML-only method of representing a checkbox's unchecked state (e.g. value=unchecked). If you wanted to submit a default value for the checkbox when it is unchecked, you could include JavaScript to create a [<input type="hidden">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden) within the form with a value indicating an unchecked state.

**Comment by totaltrash** [comment]
Hi @germsvel thanks for your reply. Yes totally understand that, in my case i have a liveview that expects nothing to be posted when all items are unchecked, which works great "in real life" but errors in PhoenixTest. I have a workaround so I'll close this issue and the PR
