### ISSUE TITLE
Handle input/select `phx-click` outside of forms

### ISSUE THREAD

**Issue by germsvel** [germsvel/phoenix_test#112]
So far, our inputs and select dropdowns work _inside_ forms. 

But in LiveView, it's possible for them to send events to the server outside of forms with `phx-click` attributes. 

- [ ] checkboxes (PR #109)
- [x] select's options
- [x] radio buttons

Note: I originally thought we might be able to handle `phx-change` on text inputs, but it seems like [that's a form-only event handler](https://hexdocs.pm/phoenix_live_view/html-attrs.html#form-event-handlers)

**Comment by alexslade** [comment]
@germsvel LiveView also supports phx-change on the select itself, without a form. 

Would you be open to a PR that supports this? I've had a poke around, looks like I might have to dig into ActiveForm tracking, to handle cases like this. 

If you've got any quick insights let me know, and I can have a run at it.
