### ISSUE TITLE
Allow form helper labels to have `exact` option

### ISSUE THREAD

**Issue by germsvel** [germsvel/phoenix_test#127]
Right now, the form helpers (e.g. `fill_in`, `select`, etc.) do not accept an option `exact: true` or `exact: false`. 

It'd be nice to support that since some labels have additional data in them (for example, see #107)

So, we want to add that `:exact` option. How should it behave? 

This is what I said in #118 

> My guess is that we should make exact: true the default for select. That's my guess based on the "principle of least surprise". It's kind of gut feeling, but I always ask myself, "what would a user expect to be the default here?"

> In this case, I think we typically write the full label name -- so we're typically trying to do exact matches. That's different from assertions, where I think we're typically trying to do an inexact match (which is why the default there is false)

So, I think we should introduce the `:exact` option, default it to `true`, but provide the option to set it to `exact: false`. 

Question: I wonder if others have thoughts on the default being set to `false` -- perhaps to allow for more flexible selections by default? 

Work to be done
----------------

- [x] `fill_in`
- [x] `select` (in #118) 
- [x] `check` and `uncheck`
- [x] `choose`
- [x] `upload`

**Comment by ftes** [comment]
I just noticed:
For `select` we use the `exact` option both for finding the input and for finding the option.
There might be cases where one would want to configure those independently (exact label, not-exact option).

**Comment by germsvel** [comment]
@ftes yeah, I noticed that yesterday as I was refactoring (in cb19f86) to allow passing `exact` to the other form helpers. 

In all other cases, the `exact` flag is acting on the label. In the `select` it's not really clear which it should act upon. 

So, we could do a couple of things: 

1. Add another option to select. Something like `exact_option`. 
2. Explain in docs that the `exact` flag acts upon both the option and the select. Still leaves an edge case where people might legitimately want an exact option name but an inexact label (e.g. the label has a `*` or something else in it). So this doesn't seem like the best option. 
3. We wait until I can figure out selectors (something I'm trying to introduce, and I'm already moving some code towards that underneath the hood) so that people can "drop down" one level when they want, and write it like this: 

```elixir
select(option("option here", exact: true, from: label("Label here", exact: true))
```

In that case, both the `option/2` and `label/2` take an `:exact` option that acts correctly. 

But that might take me a minute to get together. 

--- 

So, what do to now? My guess is we do (1) and then over time expose (3). What do you think?

**Comment by ftes** [comment]
> My guess is we do (1) and then over time expose (3). What do you think?

Agreed. And I can't wait to have `selector`s 🥳

**Comment by germsvel** [comment]
@ftes I think I'm coming full circle on #118 and realizing that _maybe_ the option text should _always_ be exact. Are there truly cases when we don't want the option element to be inexact? It's not like the option text has nested HTML inside it. 

Labels can have odd values inside them (like `<span>*</span>` for required fields, etc.), so in my mind, it makes sense to have that. 

But... should `<option>`'s be so flexible? 

Maybe #118 was really just fixing a bug -- not adding a new feature. And so, we shouldn't introduce an `exact_option` here. Feels weird.

**Comment by germsvel** [comment]
Finished this work in #129. Closing this. Let me know if there's anything you think I missed.
