### ISSUE TITLE
How to fill in inputs_for

### ISSUE THREAD

**Issue by andrewtimberlake** [germsvel/phoenix_test#133]
I’m not sure if there’s a better place to ask questions.
When using inputs_for for a multiple inputs where each iteration is still an open form, how do you target each input with `fill_in`?

Example html:

```html
<div>
<label>Name: <input name="model[0][name]" id="model_0_name" /></label>
</div>
<div>
<label>Name: <input name="model[1][name]" id="model_1_name" /></label>
</div>
```

```elixir
conn |> fill_in("model[0][name]", "Name", with: "John Doe")
** (ArgumentError) Found many labels with text "Name":
```

**Comment by germsvel** [comment]
Hmmm. That's interesting. That may be a case we missed. 

@andrewtimberlake if you try the same thing but have the labels and inputs separated, does it work? I think it might have to do wih the implicit label <> input association (which we should handle)

In other words, does it work if it's like this? 

```html
<div>
<label for="model_0_name">Name:</label> <input name="model[0][name]" id="model_0_name" />
</div>
<div>
<label for="model_1_name">Name:</label> <input name="model[1][name]" id="model_1_name" />
</div>
```

**Comment by andrewtimberlake** [comment]
They are actually separate. I’m using the `<.input />` component (my example above was a simplified example using HTML as I tend to write it by hand.
The problem is that there are multiple labels with the same name

**Comment by germsvel** [comment]
That sounds like a bug in that case -- but it's weird because that's exactly what our tests are testing. I wonder if there's something odd with `inputs_for`. 

Can you confirm you're using v0.4.0, and is there a chance you could create a simple app that reproduces the error?

**Comment by andrewtimberlake** [comment]
I have created a simple app that demonstrates what I’m trying to do:
https://github.com/andrewtimberlake/phoenix_test_inputs_for
Form at http://localhost:4000/test
Test in test/phoenix_test_inputs_for_web/live/test_live_test.exs

**Comment by andrewtimberlake** [comment]
Thanks for the help.
In that same test, I used a label and a checkbox to add a new item because I couldn’t get the example from the Phoenix docs to work, how do I test with a button like this:
```elixir
<button type="button" name="model[items][]" value="new" phx-click={JS.dispatch("change")}>
  add more
</button>
```
See: https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#inputs_for/1-dynamically-adding-and-removing-inputs

**Comment by germsvel** [comment]
@andrewtimberlake any chance you could create a simple app (or modify the one you already shared) to reproduce the error you're running into?

**Comment by germsvel** [comment]
Thanks @andrewtimberlake. The error you're seeing comes from LiveViewTest. 

Unfortunately, LiveViewTest doesn't support performing a `render_click` (which triggers the `phx-click`) with something that _only_ uses [`JS.dispatch`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.JS.html#dispatch/2) (which is dispatching a JavaScript event to the DOM). 

You can see that by running this LiveViewTest: 

```elixir
  test "add items", %{conn: conn} do
    {:ok, view, _html} = live(conn, "/test")

    html =
      view
      |> element("button", "add more")
      |> render_click()

    assert html =~ "Item 1"
  end
```

It fails with the same error: 

>      ** (ArgumentError) no push or navigation command found within JS commands: [["dispatch",{"event":"change"}]]


If you were to use something like `JS.push("change")`, then the test would send the "change" event to the LiveView. 

Does that make sense?

**Comment by andrewtimberlake** [comment]
Thanks for your help. I’ll see if it’s something we can fix in LiveView itself.

**Comment by germsvel** [comment]
@andrewtimberlake happy to help. Just FYI, I don't know if LiveViewTest will be able to fix it either because a `JS.dispatch/1` is dispatching events to the DOM, and LiveViewTest doesn't test JavaScript logic.
