### ISSUE TITLE
LiveView 1.0.0 and 'main': not compiling

### ISSUE THREAD

**Issue by mxgrn** [germsvel/phoenix_test#157]
Maybe it's no news, but just in case: I just tried 'main' in hope that I could use phoenix_test with LV 1.0.0.

It isn't compiling:

```
== Compilation error in file lib/phoenix_test/live.ex ==
** (RuntimeError) module attribute @endpoint not set for socket/2
    (phoenix 1.7.17) lib/phoenix/test/channel_test.ex:321: Phoenix.ChannelTest."MACRO-connect"/4
    (phoenix 1.7.17) expanding macro: Phoenix.ChannelTest.connect/2
    lib/phoenix_test/live.ex:225: PhoenixTest.Live.upload/5
    (phoenix_live_view 1.0.0) expanding macro: Phoenix.LiveViewTest.file_input/4
    lib/phoenix_test/live.ex:225: PhoenixTest.Live.upload/5
    (elixir 1.17.3) expanding macro: Kernel.|>/2
    lib/phoenix_test/live.ex:225: PhoenixTest.Live.upload/5
    (elixir 1.17.3) expanding macro: Kernel.|>/2
could not compile dependency :phoenix_test, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile phoenix_test --force", update it with "mix deps.update phoenix_test" or clean it with "mix deps.clean phoenix_test"
```

I haven't tried it on a vanilla phoenix project though, but let me know if I should, as it may have something to do with how my app's testing is set up.

**Comment by alexslade** [comment]
FYI I have a project running fine on LiveView v1.0.0, PhoenixTest v0.4.2

**Comment by germsvel** [comment]
@mxgrn that looks like the endpoint isn't set. Could you confirm that you have an endpoint configured in `config/test.exs`? 

```elixir
config :phoenix_test, :endpoint, MyAppWeb.Endpoint
```

**Comment by mxgrn** [comment]
Thanks! I won't try to reproduce it anymore, but I'm sure it was something on my side. Let it sit here for the record, closing.

**Comment by matt-savvy** [comment]
> [@mxgrn](https://github.com/mxgrn) that looks like the endpoint isn't set. Could you confirm that you have an endpoint configured in `config/test.exs`?
> 
> config :phoenix_test, :endpoint, MyAppWeb.Endpoint

For anyone finding this issue later, this fixed it for me.
