### ISSUE TITLE
Handle LiveView embedded in a Controller?

### ISSUE THREAD

**Issue by mayel** [germsvel/phoenix_test#16]
Awesome lib! thanks for building it :) 

I'm trying to test a form in a LiveView that's embedded in a controller with https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Controller.html#live_render/3 and getting this error, not sure if it should be using the static driver instead or if it should just fallback to regular form submission for forms without `phx-submit`?
```
     ** (ArgumentError) element selected by "#signup-form" does not have phx-submit attribute
     code: |> click_button("Sign up") 
       (phoenix_live_view 0.20.1) lib/phoenix_live_view/test/live_view_test.ex:1098: Phoenix.LiveViewTest.call/2
       (phoenix_test 0.2.2) lib/phoenix_test/live.ex:95: PhoenixTest.Driver.PhoenixTest.Live.submit_active_form/1

**Comment by germsvel** [comment]
Hi @mayel thanks for opening this issue! Can you share a little bit more about how your form itself is structured? (any and all code samples would be very helpful!).

**Comment by mayel** [comment]
Sure thing! You'll find the controller and the (Surface-powered) liveview here: https://github.com/bonfire-networks/bonfire_ui_me/tree/main/lib/views/signup

**Comment by germsvel** [comment]
@mayel I took a quick look at that repo, but I'm not familiar with Surface (I know what it is, just haven't used it). I see three files, but none of them have the actual HTML form. 

Is the form rendered inside a LiveView but it's making a regular submit? Can you provide a little more code, or if possible, a little sample repo that reproduces the error you're seeing?

**Comment by mayel** [comment]
Apologies, I forgot the form itself was in a component: https://github.com/bonfire-networks/bonfire_ui_me/blob/main/lib/components/signup/signup_form_live.sface#L40

Here's the documentation for Surface's Form (which is simply a wrapper for `Phoenix.HTML.Form.form_for`): https://surface-ui.org/builtincomponents/Form

**Comment by mayel** [comment]
I've also shared the actual HTML of the form in #17

**Comment by mayel** [comment]
> Is the form rendered inside a LiveView but it's making a regular submit?

yes sort of, it's rendered inside of a liveview which is inside of a static controller, and making a regular submit

**Comment by germsvel** [comment]
> yes sort of, it's rendered inside of a liveview which is inside of a static controller (so it's not actually "live"), and making a regular submit

Interesting. I wonder if it's confused because we're in a LiveView but it's a regular submit. I don't think I properly accounted for that, but I think that's something we should handle.

**Comment by mayel** [comment]
Yeah that's what I assumed. IMO it makes sense to fallback to regular submit when there's no `phx-submit`. That way you probably don't need any special handling for non-live-liveview as well.

**Comment by mayel** [comment]
I tried upgrading to the latest LiveView and also changing the action from "#" to "?" to no effect.
