### ISSUE TITLE
How to test a redirect after form submission?

### ISSUE THREAD

**Issue by randycoulman** [germsvel/phoenix_test#19]
I'm testing an app that renders a LiveView form and then navigates to another route after submission. How would I test this with PhoenixTest?

It seems like maybe `click_button`/`submit_form` should also follow redirects like `click_link` does, but I'm not sure what other implications that might have.

**Comment by germsvel** [comment]
Yeah, this is a great point @randycoulman. Forms should follow redirects. 

I'd like to write a test to capture this. Is this a form doing a `phx-submit` and then the LiveView does a `push_navigate`?

**Comment by randycoulman** [comment]
@germsvel You've already addressed it, but yes: `phx-sumbit` followed by `push_navigate`. I'll try out your changes today and see how they work for my app.

**Comment by randycoulman** [comment]
@germsvel 👌 Your changes worked great for my use case! I was able to fully port over to using PhoenixTest for my (still very small) app.

Thanks for this library! Very nice to use!

**Comment by germsvel** [comment]
🎉 Thanks for porting your library to use PhoenixTest @randycoulman! And thanks for coming here when you find issues.

**Comment by TommasoAmici** [comment]
Hey, I'm trying to do the same (`phx-submit` + `push_navigate`), but I'm getting an error. I'm unsure if it's something I'm doing wrong or if it's the same problem discussed here.

```ex
  def handle_event("submit", %{"form" => params}, socket) do
    case AshPhoenix.Form.submit(socket.assigns.form, params: params) do
      {:ok, league} ->
        socket =
          socket
          |> push_navigate(to: league_url(league))

        {:noreply, socket}

      {:error, form} -> ...
    end
  end
```

In my test I get this error:
```
     ** (FunctionClauseError) no function clause matching in PhoenixTest.Live.maybe_redirect/2

     The following arguments were given to PhoenixTest.Live.maybe_redirect/2:

         # 1
         {:error, :nosession}

         # 2
         %PhoenixTest.Live{view: #Phoenix.LiveViewTest.View<id: ...

     Attempted function clauses (showing 4 out of 4):

         defp maybe_redirect({:error, {kind, %{to: path}}} = result, session) when kind === :redirect or kind === :live_redirect
         defp maybe_redirect({:ok, view, _}, session)
         defp maybe_redirect({:ok, conn}, _session)
         defp maybe_redirect(html, session) when is_binary(html)
```

If I replace `push_navigate` with `redirect` everything works correctly

**Comment by TommasoAmici** [comment]
it took me a long time, but the reason this was failing like so is because I was using `push_navigate` with a URL that wasn't a live view.

When using the app in the browser this was not a problem, but in tests with `phoenix_test` it resulted in that error.

I wonder if we can match on `{:error, :nosession}` and suggest a better error message. I'm not sure if `:nosession` can come up in other scenarios though
