### ISSUE TITLE
Improve documentation for function using @doc 

### ISSUE THREAD

**Issue by lcezermf** [germsvel/phoenix_test#29]
Overall the code is pretty clean and straightforward but do you @germsvel think that would be useful to improve the doc on the modules and functions? If that is the case I can work on and submit a PR.

**Comment by germsvel** [comment]
@lcezermf always happy to look at a PR that improves docs. I think those could use some love for sure. Thanks for asking!

**Comment by lcezermf** [comment]
Nice, I will submit something in the next days, thanks!

**Comment by germsvel** [comment]
👍 I'll go ahead and close this since it's not an active issue, but I'll be happy to review PRs!
