### ISSUE TITLE
Would it be possible to relax Elixir requirement?

### ISSUE THREAD

**Issue by tshakah** [germsvel/phoenix_test#38]
Would it be possible to relax the required Elixir version so projects using this library don't have to be on 1.16?

https://github.com/germsvel/phoenix_test/blob/b8520142aa459dd6264fe13ae846dfc05323c8e0/mix.exs#L17

**Comment by germsvel** [comment]
Yeah, that's something I haven't tested yet (I've only tested it with Elixir 1.16), but I agree that it's probably something we would want to relax (at least to 1.15) if possible.

**Comment by tshakah** [comment]
1.15 would work for me, as that's what the app I was trying `phoenix_test` with was using

**Comment by germsvel** [comment]
I tried relaxing to 1.14, but there seem to be some `mix format` differences. So, for now, we'll just support 1.15.

**Comment by tshakah** [comment]
Thank you!
