### ISSUE TITLE
asserting on page title?

### ISSUE THREAD

**Issue by rgraff** [germsvel/phoenix_test#4]
Is it possible to assert on the page title with `assert_has`?

**Comment by rgraff** [comment]
Might need a `assert_page_title` that uses the LiveView page title. I took a quick look at how to implement myself but it wasn't obvious.

**Comment by germsvel** [comment]
Yeah, I'd hate to have to add a new assertion function, but I know assertions start by getting the HTML from the drivers. We could also have a special case when `assert_has` takes in a `"title"`. So, I'll consider looking into that.

**Comment by lcezermf** [comment]
I was trying to debug and it seems the `<title>` element is not returned by the HTML when using LiveView. According to the docs here: https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#live_title/1 it is assigned to the socket directly.

**Comment by lcezermf** [comment]
Well, based on my current project we test this as a whole. Normally the page titles are not that big, eg: "Company name | Page title", so we test the whole string.

**Comment by rgraff** [comment]
@germsvel my expectation is that it'd match on the whole string.  A future improvement to `assert_has` could be a regex.

```elixir
|> assert_has("title", ~r/PhoenixTest/)
```

**Comment by germsvel** [comment]
Thanks @rgraff and @lcezermf. The ability to assert/refute on title is on `main`, and it'll be out in the next release. 🎉
