### ISSUE TITLE
Support `phx-trigger-action`

### ISSUE THREAD

**Issue by totaltrash** [germsvel/phoenix_test#47]
I'm not sure if this is something that can be supported but it doesn't appear to work at the moment.

I've got a form in a live view that submits to a controller when `phx-trigger-action` resolves to true, as explained [here](https://hexdocs.pm/phoenix_live_view/form-bindings.html#submitting-the-form-action-over-http). This pattern lets you use liveview for realtime form validation, then submit the form to a controller where controller stuff needs to happen (interacting with the conn). Currently the form is not submitted when triggered using phoenix_test.

It seems like something that would fit right in to the phoenix_test wheelhouse, testing an interaction between liveviews and controllers.

**Comment by germsvel** [comment]
Thanks for opening this issue (and the PR) @totaltrash! I think this would be a great addition to PhoenixTest.

**Comment by goncalotomas** [comment]
Just bumped into this after struggling to understand why testing out a registration form with phoenix_test wasn't working for me. I don't know exactly what's needed to add support for this, but with some guidance I would love to add a PR that fixed this.
