### ISSUE TITLE
Static form submits don't include all pre-rendered data

### ISSUE THREAD

**Issue by ftes** [germsvel/phoenix_test#57]
## Expected

Given a form

```html
<form>
  <input name="input" value="value" />

  <select name="select">
    <option value="not_selected">Not selected</option>
    <option value="selected" selected>Selected</option>
  </select>

  <input name="checkbox" type="checkbox" value="not_checked" />
  <input name="checkbox" type="checkbox" value="checked" checked />

  <input name="radio" type="radio" value="not_checked" />
  <input name="radio" type="radio" value="checked" checked />
</form>
```

I expect `submit_form/3` to submit the following data

```html
input=value
select=selected
checkbox=checked
radio=checked
```

for all of these cases:
- ❌  static form in static view
- ❌  static form in live view
- ✅  live form in live view.

## Actual
For static forms (both in static and live view), only this data is submitted:

```html
radio=checked
```

**Comment by germsvel** [comment]
Great catch @ftes! Thanks for opening this issue. I think this should be somewhat straightforward to add.

**Comment by ftes** [comment]
Neat. I opened #58 with failing tests. Didn't look into fixing it yet.
If you're on it: great! If you're tight on time, let me know and I'll be happy to dig further.
