### ISSUE TITLE
"static pages" wording in the README.md

### ISSUE THREAD

**Issue by michallepicki** [germsvel/phoenix_test#6]
Hello!

I don't want to be nitpicky, but I think the meaning of this term is much more specific than what you meant there. A few examples (there are more):

> If I’m going to write a static page, I use regular controllers + views/HTML modules.

> But if we're testing a page is static, we have to resort to controller testing:

Dynamic web pages that are server-side rendered using regular Phoenix controllers ("dead views") are affected by the same problems as you describe. I'm sure that you use them as well and this exact more general category of such non-liveview pages is what you meant by "static pages" there, but I think calling them "static pages" may be confusing (especially to less experienced developers)

**Comment by michallepicki** [comment]
I like "non-liveview" as well. Maybe it'll be sounding a bit repetitive to talk about LiveView and non-LiveView pages/views all the time, but I also can't think of a better alternative. For me personally those are also "normal" / "regular" Phoenix views/pages, but maybe for someone else LiveViews are the "normal" ones, I don't know. "Traditional" also comes to mind

**Comment by germsvel** [comment]
@michallepicki I opted for adding a note in the README to clarify what "static" means and what it doesn't. Since we can't find a better term for now, I'll stick with static. But I realize it's easily confused with static-site generated pages (e.g. Jekyll, Gatsby, etc.).
