### ISSUE TITLE
Select field with multiple attribute in forms raises error

### ISSUE THREAD

**Issue by sasikumar87** [germsvel/phoenix_test#70]
Currently when encountering multi-select forms, it raises `** (ArgumentError) could not find non-disabled input, select or textarea` error

**Comment by germsvel** [comment]
Hi @sasikumar87 thanks for opening this issue! I know multi-select form is something we haven't yet handled. Could you share a sample of the form select you're trying to select? It would be a helpful starting point.

**Comment by sasikumar87** [comment]
I'll give an attempt to solve it first
